Chikorita:
- grass
Bayleef:
- grass
Meganium:
- grass
Cyndaquil:
- fire
Quilava:
- fire
Typhlosion:
- fire
Totodile:
- water
Croconaw:
- water
Feraligatr:
- water
Sentret:
- normal
Furret:
- normal
Hoothoot:
- normal
- flying
Noctowl:
- normal
- flying
Ledyba:
- bug
- flying
Ledian:
- bug
- flying
Spinarak:
- bug
- poison
Ariados:
- bug
- poison
Crobat:
- poison
- flying
Chinchou:
- water
- electric
Lanturn:
- water
- electric
Pichu:
- electric
Cleffa:
- fairy
Igglybuff:
- normal
- fairy
Togepi:
- fairy
Togetic:
- fairy
- flying
Natu:
- psychic
- flying
Xatu:
- psychic
- flying
Mareep:
- electric
Flaaffy:
- electric
Ampharos:
- electric
Bellossom:
- grass
Marill:
- water
- fairy
Azumarill:
- water
- fairy
Sudowoodo:
- rock
Politoed:
- water
Hoppip:
- grass
- flying
Skiploom:
- grass
- flying
Jumpluff:
- grass
- flying
Aipom:
- normal
Sunkern:
- grass
Sunflora:
- grass
Yanma:
- bug
- flying
Wooper:
- water
- ground
Quagsire:
- water
- ground
Espeon:
- psychic
Umbreon:
- dark
Murkrow:
- dark
- flying
Slowking:
- water
- psychic
Misdreavus:
- ghost
Unown:
- psychic
Wobbuffet:
- psychic
Girafarig:
- normal
- psychic
Pineco:
- bug
Forretress:
- bug
- steel
Dunsparce:
- normal
Gligar:
- ground
- flying
Steelix:
- steel
- ground
Snubbull:
- fairy
Granbull:
- fairy
Qwilfish:
- water
- poison
Scizor:
- bug
- steel
Shuckle:
- bug
- rock
Heracross:
- bug
- fighting
Sneasel:
- dark
- ice
Teddiursa:
- normal
Ursaring:
- normal
Slugma:
- fire
Magcargo:
- fire
- rock
Swinub:
- ice
- ground
Piloswine:
- ice
- ground
Corsola:
- water
- rock
Remoraid:
- water
Octillery:
- water
Delibird:
- ice
- flying
Mantine:
- water
- flying
Skarmory:
- steel
- flying
Houndour:
- dark
- fire
Houndoom:
- dark
- fire
Kingdra:
- water
- dragon
Phanpy:
- ground
Donphan:
- ground
Porygon2:
- normal
Stantler:
- normal
Smeargle:
- normal
Tyrogue:
- fighting
Hitmontop:
- fighting
Smoochum:
- ice
- psychic
Elekid:
- electric
Magby:
- fire
Miltank:
- normal
Blissey:
- normal
Raikou:
- electric
Entei:
- fire
Suicune:
- water
Larvitar:
- rock
- ground
Pupitar:
- rock
- ground
Tyranitar:
- rock
- dark
Lugia:
- psychic
- flying
Ho-Oh:
- fire
- flying
Celebi:
- psychic
- grass