Treecko:
- grass
Grovyle:
- grass
Sceptile:
- grass
Torchic:
- fire
Combusken:
- fire
- fighting
Blaziken:
- fire
- fighting
Mudkip:
- water
Marshtomp:
- water
- ground
Swampert:
- water
- ground
Poochyena:
- dark
Mightyena:
- dark
Zigzagoon:
- normal
Linoone:
- normal
Wurmple:
- bug
Silcoon:
- bug
Beautifly:
- bug
- flying
Cascoon:
- bug
Dustox:
- bug
- poison
Lotad:
- water
- grass
Lombre:
- water
- grass
Ludicolo:
- water
- grass
Seedot:
- grass
Nuzleaf:
- grass
- dark
Shiftry:
- grass
- dark
Taillow:
- normal
- flying
Swellow:
- normal
- flying
Wingull:
- water
- flying
Pelipper:
- water
- flying
Ralts:
- psychic
- fairy
Kirlia:
- psychic
- fairy
Gardevoir:
- psychic
- fairy
Surskit:
- bug
- water
Masquerain:
- bug
- flying
Shroomish:
- grass
Breloom:
- grass
- fighting
Slakoth:
- normal
Vigoroth:
- normal
Slaking:
- normal
Nincada:
- bug
- ground
Ninjask:
- bug
- flying
Shedinja:
- bug
- ghost
Whismur:
- normal
Loudred:
- normal
Exploud:
- normal
Makuhita:
- fighting
Hariyama:
- fighting
Azurill:
- normal
- fairy
Nosepass:
- rock
Skitty:
- normal
Delcatty:
- normal
Sableye:
- dark
- ghost
Mawile:
- steel
- fairy
Aron:
- steel
- rock
Lairon:
- steel
- rock
Aggron:
- steel
- rock
Meditite:
- fighting
- psychic
Medicham:
- fighting
- psychic
Electrike:
- electric
Manectric:
- electric
Plusle:
- electric
Minun:
- electric
Volbeat:
- bug
Illumise:
- bug
Roselia:
- grass
- poison
Gulpin:
- poison
Swalot:
- poison
Carvanha:
- water
- dark
Sharpedo:
- water
- dark
Wailmer:
- water
Wailord:
- water
Numel:
- fire
- ground
Camerupt:
- fire
- ground
Torkoal:
- fire
Spoink:
- psychic
Grumpig:
- psychic
Spinda:
- normal
Trapinch:
- ground
Vibrava:
- ground
- dragon
Flygon:
- ground
- dragon
Cacnea:
- grass
Cacturne:
- grass
- dark
Swablu:
- normal
- flying
Altaria:
- dragon
- flying
Zangoose:
- normal
Seviper:
- poison
Lunatone:
- rock
- psychic
Solrock:
- rock
- psychic
Barboach:
- water
- ground
Whiscash:
- water
- ground
Corphish:
- water
Crawdaunt:
- water
- dark
Baltoy:
- ground
- psychic
Claydol:
- ground
- psychic
Lileep:
- rock
- grass
Cradily:
- rock
- grass
Anorith:
- rock
- bug
Armaldo:
- rock
- bug
Feebas:
- water
Milotic:
- water
Castform:
- normal
Kecleon:
- normal
Shuppet:
- ghost
Banette:
- ghost
Duskull:
- ghost
Dusclops:
- ghost
Tropius:
- grass
- flying
Chimecho:
- psychic
Absol:
- dark
Wynaut:
- psychic
Snorunt:
- ice
Glalie:
- ice
Spheal:
- ice
- water
Sealeo:
- ice
- water
Walrein:
- ice
- water
Clamperl:
- water
Huntail:
- water
Gorebyss:
- water
Relicanth:
- water
- rock
Luvdisc:
- water
Bagon:
- dragon
Shelgon:
- dragon
Salamence:
- dragon
- flying
Beldum:
- steel
- psychic
Metang:
- steel
- psychic
Metagross:
- steel
- psychic
Regirock:
- rock
Regice:
- ice
Registeel:
- steel
Latias:
- dragon
- psychic
Latios:
- dragon
- psychic
Kyogre:
- water
Groudon:
- ground
Rayquaza:
- dragon
- flying
Jirachi:
- steel
- psychic
Deoxys:
- psychic