Chespin:
- grass
Quilladin:
- grass
Chesnaught:
- grass
- fighting
Fennekin:
- fire
Braixen:
- fire
Delphox:
- fire
- psychic
Froakie:
- water
Frogadier:
- water
Greninja:
- water
- dark
Bunnelby:
- normal
Diggersby:
- normal
- ground
Fletchling:
- normal
- flying
Fletchinder:
- fire
- flying
Talonflame:
- fire
- flying
Scatterbug:
- bug
Spewpa:
- bug
Vivillon:
- bug
- flying
Litleo:
- fire
- normal
Pyroar:
- fire
- normal
Flabébé:
- fairy
Floette:
- fairy
Florges:
- fairy
Skiddo:
- grass
Gogoat:
- grass
Pancham:
- fighting
Pangoro:
- fighting
- dark
Furfrou:
- normal
Espurr:
- psychic
Meowstic:
- psychic
Honedge:
- steel
- ghost
Doublade:
- steel
- ghost
Aegislash:
- steel
- ghost
Spritzee:
- fairy
Aromatisse:
- fairy
Swirlix:
- fairy
Slurpuff:
- fairy
Inkay:
- dark
- psychic
Malamar:
- dark
- psychic
Binacle:
- rock
- water
Barbaracle:
- rock
- water
Skrelp:
- poison
- water
Dragalge:
- poison
- dragon
Clauncher:
- water
Clawitzer:
- water
Helioptile:
- electric
- normal
Heliolisk:
- electric
- normal
Tyrunt:
- rock
- dragon
Tyrantrum:
- rock
- dragon
Amaura:
- rock
- ice
Aurorus:
- rock
- ice
Sylveon:
- fairy
Hawlucha:
- fighting
- flying
Dedenne:
- electric
- fairy
Carbink:
- rock
- fairy
Goomy:
- dragon
Sliggoo:
- dragon
Goodra:
- dragon
Klefki:
- steel
- fairy
Phantump:
- ghost
- grass
Trevenant:
- ghost
- grass
Pumpkaboo:
- ghost
- grass
Gourgeist:
- ghost
- grass
Bergmite:
- ice
Avalugg:
- ice
Noibat:
- flying
- dragon
Noivern:
- flying
- dragon
Xerneas:
- fairy
Yveltal:
- dark
- flying
Zygarde:
- dragon
- ground
Diancie:
- rock
- fairy
Hoopa:
- psychic
- ghost
Volcanion:
- fire
- water