Victini:
- psychic
- fire
Snivy:
- grass
Servine:
- grass
Serperior:
- grass
Tepig:
- fire
Pignite:
- fire
- fighting
Emboar:
- fire
- fighting
Oshawott:
- water
Dewott:
- water
Samurott:
- water
Patrat:
- normal
Watchog:
- normal
Lillipup:
- normal
Herdier:
- normal
Stoutland:
- normal
Purrloin:
- dark
Liepard:
- dark
Pansage:
- grass
Simisage:
- grass
Pansear:
- fire
Simisear:
- fire
Panpour:
- water
Simipour:
- water
Munna:
- psychic
Musharna:
- psychic
Pidove:
- normal
- flying
Tranquill:
- normal
- flying
Unfezant:
- normal
- flying
Blitzle:
- electric
Zebstrika:
- electric
Roggenrola:
- rock
Boldore:
- rock
Gigalith:
- rock
Woobat:
- psychic
- flying
Swoobat:
- psychic
- flying
Drilbur:
- ground
Excadrill:
- ground
- steel
Audino:
- normal
Timburr:
- fighting
Gurdurr:
- fighting
Conkeldurr:
- fighting
Tympole:
- water
Palpitoad:
- water
- ground
Seismitoad:
- water
- ground
Throh:
- fighting
Sawk:
- fighting
Sewaddle:
- bug
- grass
Swadloon:
- bug
- grass
Leavanny:
- bug
- grass
Venipede:
- bug
- poison
Whirlipede:
- bug
- poison
Scolipede:
- bug
- poison
Cottonee:
- grass
- fairy
Whimsicott:
- grass
- fairy
Petilil:
- grass
Lilligant:
- grass
Basculin:
- water
Sandile:
- ground
- dark
Krokorok:
- ground
- dark
Krookodile:
- ground
- dark
Darumaka:
- fire
Darmanitan:
- fire
- fire
Maractus:
- grass
Dwebble:
- bug
- rock
Crustle:
- bug
- rock
Scraggy:
- dark
- fighting
Scrafty:
- dark
- fighting
Sigilyph:
- psychic
- flying
Yamask:
- ghost
Cofagrigus:
- ghost
Tirtouga:
- water
- rock
Carracosta:
- water
- rock
Archen:
- rock
- flying
Archeops:
- rock
- flying
Trubbish:
- poison
Garbodor:
- poison
Zorua:
- dark
Zoroark:
- dark
Minccino:
- normal
Cinccino:
- normal
Gothita:
- psychic
Gothorita:
- psychic
Gothitelle:
- psychic
Solosis:
- psychic
Duosion:
- psychic
Reuniclus:
- psychic
Ducklett:
- water
- flying
Swanna:
- water
- flying
Vanillite:
- ice
Vanillish:
- ice
Vanilluxe:
- ice
Deerling:
- normal
- grass
Sawsbuck:
- normal
- grass
Emolga:
- electric
- flying
Karrablast:
- bug
Escavalier:
- bug
- steel
Foongus:
- grass
- poison
Amoonguss:
- grass
- poison
Frillish:
- water
- ghost
Jellicent:
- water
- ghost
Alomomola:
- water
Joltik:
- bug
- electric
Galvantula:
- bug
- electric
Ferroseed:
- grass
- steel
Ferrothorn:
- grass
- steel
Klink:
- steel
Klang:
- steel
Klinklang:
- steel
Tynamo:
- electric
Eelektrik:
- electric
Eelektross:
- electric
Elgyem:
- psychic
Beheeyem:
- psychic
Litwick:
- ghost
- fire
Lampent:
- ghost
- fire
Chandelure:
- ghost
- fire
Axew:
- dragon
Fraxure:
- dragon
Haxorus:
- dragon
Cubchoo:
- ice
Beartic:
- ice
Cryogonal:
- ice
Shelmet:
- bug
Accelgor:
- bug
Stunfisk:
- ground
- electric
Mienfoo:
- fighting
Mienshao:
- fighting
Druddigon:
- dragon
Golett:
- ground
- ghost
Golurk:
- ground
- ghost
Pawniard:
- dark
- steel
Bisharp:
- dark
- steel
Bouffalant:
- normal
Rufflet:
- normal
- flying
Braviary:
- normal
- flying
Vullaby:
- dark
- flying
Mandibuzz:
- dark
- flying
Heatmor:
- fire
Durant:
- bug
- steel
Deino:
- dark
- dragon
Zweilous:
- dark
- dragon
Hydreigon:
- dark
- dragon
Larvesta:
- bug
- fire
Volcarona:
- bug
- fire
Cobalion:
- steel
- fighting
Terrakion:
- rock
- fighting
Virizion:
- grass
- fighting
Tornadus:
- flying
Thundurus:
- electric
- flying
Reshiram:
- dragon
- fire
Zekrom:
- dragon
- electric
Landorus:
- ground
- flying
Kyurem:
- dragon
- ice
Keldeo:
- water
- fighting
Meloetta:
- normal
- psychic
Genesect:
- bug
- steel