Rowlet:
- grass
- flying
Dartrix:
- grass
- flying
Decidueye:
- grass
- ghost
Litten:
- fire
Torracat:
- fire
Incineroar:
- fire
- dark
Popplio:
- water
Brionne:
- water
Primarina:
- water
- fairy
Pikipek:
- normal
- flying
Trumbeak:
- normal
- flying
Toucannon:
- normal
- flying
Yungoos:
- normal
Gumshoos:
- normal
Grubbin:
- bug
Charjabug:
- bug
- electric
Vikavolt:
- bug
- electric
Crabrawler:
- fighting
Crabominable:
- fighting
- ice
Oricorio:
- fire
- flying
Cutiefly:
- bug
- fairy
Ribombee:
- bug
- fairy
Rockruff:
- rock
Lycanroc:
- rock
Wishiwashi:
- water
Mareanie:
- poison
- water
Toxapex:
- poison
- water
Mudbray:
- ground
Mudsdale:
- ground
Dewpider:
- water
- bug
Araquanid:
- water
- bug
Fomantis:
- grass
Lurantis:
- grass
Morelull:
- grass
- fairy
Shiinotic:
- grass
- fairy
Salandit:
- poison
- fire
Salazzle:
- poison
- fire
Stufful:
- normal
- fighting
Bewear:
- normal
- fighting
Bounsweet:
- grass
Steenee:
- grass
Tsareena:
- grass
Comfey:
- fairy
Oranguru:
- normal
- psychic
Passimian:
- fighting
Wimpod:
- bug
- water
Golisopod:
- bug
- water
Sandygast:
- ghost
- ground
Palossand:
- ghost
- ground
Pyukumuku:
- water
Type Null:
- normal
Silvally:
- normal
Minior:
- rock
- flying
Komala:
- normal
Turtonator:
- fire
- dragon
Togedemaru:
- electric
- steel
Mimikyu:
- ghost
- fairy
Bruxish:
- water
- psychic
Drampa:
- normal
- dragon
Dhelmise:
- ghost
- grass
Jangmo-o:
- dragon
Hakamo-o:
- dragon
- fighting
Kommo-o:
- dragon
- fighting
Tapu Koko:
- electric
- fairy
Tapu Lele:
- psychic
- fairy
Tapu Bulu:
- grass
- fairy
Tapu Fini:
- water
- fairy
Cosmog:
- psychic
Cosmoem:
- psychic
Solgaleo:
- psychic
- steel
Lunala:
- psychic
- ghost
Nihilego:
- rock
- poison
Buzzwole:
- bug
- fighting
Pheromosa:
- bug
- fighting
Xurkitree:
- electric
Celesteela:
- steel
- flying
Kartana:
- grass
- steel
Guzzlord:
- dark
- dragon
Necrozma:
- psychic
Magearna:
- steel
- fairy