Turtwig:
- grass
Grotle:
- grass
Torterra:
- grass
- ground
Chimchar:
- fire
Monferno:
- fire
- fighting
Infernape:
- fire
- fighting
Piplup:
- water
Prinplup:
- water
Empoleon:
- water
- steel
Starly:
- normal
- flying
Staravia:
- normal
- flying
Staraptor:
- normal
- flying
Bidoof:
- normal
Bibarel:
- normal
- water
Kricketot:
- bug
Kricketune:
- bug
Shinx:
- electric
Luxio:
- electric
Luxray:
- electric
Budew:
- grass
- poison
Roserade:
- grass
- poison
Cranidos:
- rock
Rampardos:
- rock
Shieldon:
- rock
- steel
Bastiodon:
- rock
- steel
Burmy:
- bug
Wormadam:
- bug
- grass
Mothim:
- bug
- flying
Combee:
- bug
- flying
Vespiquen:
- bug
- flying
Pachirisu:
- electric
Buizel:
- water
Floatzel:
- water
Cherubi:
- grass
Cherrim:
- grass
Shellos:
- water
Gastrodon:
- water
- ground
Ambipom:
- normal
Drifloon:
- ghost
- flying
Drifblim:
- ghost
- flying
Buneary:
- normal
Lopunny:
- normal
Mismagius:
- ghost
Honchkrow:
- dark
- flying
Glameow:
- normal
Purugly:
- normal
Chingling:
- psychic
Stunky:
- poison
- dark
Skuntank:
- poison
- dark
Bronzor:
- steel
- psychic
Bronzong:
- steel
- psychic
Bonsly:
- rock
Mime Jr.:
- psychic
- fairy
Happiny:
- normal
Chatot:
- normal
- flying
Spiritomb:
- ghost
- dark
Gible:
- dragon
- ground
Gabite:
- dragon
- ground
Garchomp:
- dragon
- ground
Munchlax:
- normal
Riolu:
- fighting
Lucario:
- fighting
- steel
Hippopotas:
- ground
Hippowdon:
- ground
Skorupi:
- poison
- bug
Drapion:
- poison
- dark
Croagunk:
- poison
- fighting
Toxicroak:
- poison
- fighting
Carnivine:
- grass
Finneon:
- water
Lumineon:
- water
Mantyke:
- water
- flying
Snover:
- grass
- ice
Abomasnow:
- grass
- ice
Weavile:
- dark
- ice
Magnezone:
- electric
- steel
Lickilicky:
- normal
Rhyperior:
- ground
- rock
Tangrowth:
- grass
Electivire:
- electric
Magmortar:
- fire
Togekiss:
- fairy
- flying
Yanmega:
- bug
- flying
Leafeon:
- grass
Glaceon:
- ice
Gliscor:
- ground
- flying
Mamoswine:
- ice
- ground
Porygon-Z:
- normal
Gallade:
- psychic
- fighting
Probopass:
- rock
- steel
Dusknoir:
- ghost
Froslass:
- ice
- ghost
Rotom:
- electric
- ghost
Uxie:
- psychic
Mesprit:
- psychic
Azelf:
- psychic
Dialga:
- steel
- dragon
Palkia:
- water
- dragon
Heatran:
- fire
- steel
Regigigas:
- normal
Giratina:
- ghost
- dragon
Cresselia:
- psychic
Phione:
- water
Manaphy:
- water
Darkrai:
- dark
Shaymin:
- grass
- grass
Arceus:
- normal